### ISSUE TITLE
Invalidate metadata cache when cassandra schema changed

### ISSUE THREAD

**Issue by kulikov** [InnovaCo/binders-cassandra#13]

**Comment by vkuptcov** [comment]
Проблема гораздо более серьезная: баг  состоит не только в том, что новое поле после добавления миграций не будет возвращаться, но и в том, что может произойти смещение полей и под именем одного будет возвращаться другое. И в случае полей с null или с совпадающими типами данных это может быть очень серьезной ошибкой.

**Comment by vkuptcov** [comment]
Т.е. были в таблице поля
```
CREATE TABLE t (
  id text,
  a text,
  c text,
  d text,
  PRIMARY KEY (id)
)
```
добавили поле b, схема стала
```
CREATE TABLE t (
  id text,
  a text,
  b text,
  c text,
  d text,
  PRIMARY KEY (id)
)
```
если рестарта приложения не было, то в поле d теперь будет возвращаться поле c

**Comment by aytereschenko** [comment]
https://docs.datastax.com/en/drivers/java/2.0/index.html?com/datastax/driver/core/SchemaChangeListener.html

**Comment by maqdev** [comment]
@vkuptcov этот дефект акуален? Это же была проблема в самом драйвере?

**Comment by vkuptcov** [comment]
@maqdev дефект неактуален. Проблема строго говоря во взаимодействии драйвера и сервера C*.  Будет решена в новой версии C*
