### ISSUE TITLE
Serializable Cassandra session

### ISSUE THREAD

**Issue by ddka** [InnovaCo/binders-cassandra#15]
When using the binder-cassandra all work fine but if i try to use it e.g. as a map function in spark which needs to be serializable i get
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
....
....
Caused by: java.io.NotSerializableException: com.datastax.driver.core.SessionManager

Any suggestions or is there any serializable session to be used?

Thanks

DD

**Comment by maqdev** [comment]
Hi!

Session can't be serialized (it's a network connection. I'm not fully understand how you implement spark task (and i'm not familiar with spark closely). 

I guess that you need to move session variable out of task class (which need's to be serializable).

So you have to create/destroy session inside your map function or create and destroy session object somewhere else (may-be in some singleton object) and access it from your task class.

**Comment by ddka** [comment]
Thanks for your reply
