### ISSUE TITLE
Syntax sugar for batch statements

### ISSUE THREAD

**Issue by maqdev** [InnovaCo/binders-cassandra#5]
Something like

    object Batch {
        def apply(cqls: Statements*) = {
            val bs = new BatchStatement()
            cqls.foreach(bs.add)
            bs
        }
    }

That could be used like

`Batch(cql"abcde....", cql"....")`

Also think about BatchStatement type (LOGGED, UNLOGGED, etc)

**Comment by vkuptcov** [comment]
```  
def executeInBatch(statements: Statement[_]*): ResultSet = {
    val batch = new BatchStatement(BatchStatement.Type.UNLOGGED)
    statements.map(_.boundStatement).foreach(batch.add)
    cache.session.execute(batch)
  }
```

**Comment by aytereschenko** [comment]
:+1: Vote for this feature. As of Cassandra 2.0.6 with conditional batch updates the feature becomes really essential.

**Comment by Gems** [comment]
:+1:

**Comment by vkuptcov** [comment]
https://github.com/InnovaCo/binders-cassandra/pull/17
